
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

def send_contact_alert_to_you(name, phone, email, message) -> bool:
    try:
        msg = MIMEMultipart()
        msg['From'] = os.getenv("SENDER_MAIL")
        msg['To'] = "thirusubramaniyan2001@gmail.com"
        msg['Subject'] = f"📧 New Contact Form Submission - {name}"

        body = f'''
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #ffffff;
                    background-color: #000000;
                    margin: 0;
                    padding: 20px;
                }}
                .container {{
                    max-width: 800px;
                    margin: 0 auto;
                    background-color: #000000;
                    border: 1px solid #333;
                }}
                .header {{
                    background-color: #000000;
                    color: #ffffff;
                    padding: 20px;
                    border-bottom: 2px solid #fff;
                }}
                .content {{
                    padding: 20px;
                    background-color: #000000;
                }}
                .section {{
                    margin-bottom: 25px;
                    padding: 15px;
                    background-color: #111111;
                    border: 1px solid #333;
                    border-radius: 5px;
                }}
                .section-title {{
                    color: #ffffff;
                    border-bottom: 1px solid #333;
                    padding-bottom: 10px;
                    margin-bottom: 15px;
                    font-size: 18px;
                    font-weight: bold;
                }}
                .field {{
                    margin-bottom: 10px;
                    display: flex;
                }}
                .field-label {{
                    color: #cccccc;
                    font-weight: bold;
                    width: 200px;
                    flex-shrink: 0;
                }}
                .field-value {{
                    color: #ffffff;
                    flex-grow: 1;
                }}
                .message-content {{
                    white-space: pre-wrap;
                    background-color: #1a1a1a;
                    padding: 15px;
                    border-radius: 5px;
                    color: #ffffff;
                    line-height: 1.8;
                }}
                .footer {{
                    background-color: #000000;
                    color: #cccccc;
                    padding: 15px;
                    text-align: center;
                    border-top: 1px solid #333;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1 style="margin: 0; color: #ffffff;">📧 NEW CONTACT FORM SUBMISSION</h1>
                    <p style="margin: 5px 0 0 0; color: #cccccc;">Received on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
                </div>
                
                <div class="content">
                    
                    <!-- Contact Information -->
                    <div class="section">
                        <div class="section-title">👤 Contact Information</div>
                        <div class="field">
                            <div class="field-label">Full Name:</div>
                            <div class="field-value">{name}</div>
                        </div>
                        <div class="field">
                            <div class="field-label">Phone Number:</div>
                            <div class="field-value">{phone}</div>
                        </div>
                        <div class="field">
                            <div class="field-label">Email Address:</div>
                            <div class="field-value">{email}</div>
                        </div>
                    </div>
                    
                    <!-- Message Content -->
                    <div class="section">
                        <div class="section-title">💬 Message</div>
                        <div class="message-content">
                            {message}
                        </div>
                    </div>

                </div>

                <div class="footer">
                    This is an automated contact form alert generated by your portfolio website.
                </div>
            </div>
        </body>
        </html>
        '''
        msg.attach(MIMEText(body, 'html'))
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(os.getenv("SENDER_MAIL"), os.getenv("APP_PASSWORD"))
            server.sendmail(os.getenv("SENDER_MAIL"), "thirusubramaniyan2001@gmail.com", msg.as_string())
        print("✅ Contact alert email sent successfully")
        return True
    except Exception as e:
        print(f"❌ Error sending contact alert: {str(e)}")
        return False

def send_acknowledgement_to_user(name, user_email) -> bool:
    try:
        sender_email = os.getenv("SENDER_MAIL")
        app_password = os.getenv("APP_PASSWORD")
        if not sender_email or not app_password:
            return False        
        msg = MIMEMultipart()
        msg["From"] = sender_email
        msg["To"] = user_email
        msg["Subject"] = "Thank You for Contacting - Thirumurugan Subramaniyan"

        body = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #000000;
                    background-color: #ffffff;
                    margin: 0;
                    padding: 20px;
                }}
                .container {{
                    max-width: 700px;
                    margin: 0 auto;
                    background-color: #ffffff;
                    border: 2px solid #000000;
                }}
                .header {{
                    background-color: #000000;
                    color: #ffffff;
                    padding: 30px;
                    text-align: center;
                }}
                .content {{
                    padding: 30px;
                    background-color: #ffffff;
                }}
                .section {{
                    margin-bottom: 25px;
                }}
                .contact-info {{
                    background-color: #f5f5f5;
                    padding: 20px;
                    border: 1px solid #000000;
                    margin: 20px 0;
                }}
                .footer {{
                    background-color: #000000;
                    color: #ffffff;
                    padding: 20px;
                    text-align: center;
                }}
                .signature {{
                    margin-top: 30px;
                    border-top: 1px solid #000000;
                    padding-top: 20px;
                }}
                .response-time {{
                    background-color: #000000;
                    color: #ffffff;
                    padding: 10px;
                    text-align: center;
                    margin: 15px 0;
                    border-radius: 5px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1 style="margin: 0; font-size: 28px;">THANK YOU FOR REACHING OUT</h1>
                    <p style="margin: 5px 0 0 0; font-size: 16px; opacity: 0.9;">Your message has been received</p>
                </div>

                <div class="content">
                    <div class="section">
                        <p>Dear <strong>{name}</strong>,</p>

                        <p>Thank you for taking the time to contact me. I have successfully received your message and appreciate you reaching out.</p>

                        <div class="response-time">
                            <strong>⏰ Response Time:</strong> I typically respond within 24 hours
                        </div>

                        <p>I will review your message carefully and get back to you as soon as possible. 
                        If your inquiry is urgent, please feel free to contact me directly via phone.</p>
                    </div>

                    <div class="contact-info">
                        <h3 style="margin-top: 0; color: #000000;">📞 Direct Contact Information</h3>
                        <p><strong>📧 Email:</strong> thirusubramaniyan2001@gmail.com</p>
                        <p><strong>📱 Phone:</strong> +91 7339225958</p>
                        <p><strong>📍 Location:</strong> Chennai, Tamil Nadu</p>
                        
                        <h4 style="color: #000000; margin-top: 20px;">🔗 Professional Profiles</h4>
                        <p>
                            <strong>LinkedIn:</strong> 
                            <a href="https://www.linkedin.com/in/thirumurugan-subramaniyan-a62351212/" 
                               style="color: #000000; text-decoration: none;">
                               linkedin.com/in/thirumurugan-subramaniyan
                            </a>
                        </p>
                        <p>
                            <strong>GitHub:</strong> 
                            <a href="https://github.com/thirumurugan2001" 
                               style="color: #000000; text-decoration: none;">
                               github.com/thirumurugan2001
                            </a>
                        </p>
                        <p>
                            <strong>Portfolio:</strong> 
                            <a href="https://thirumurugan2001.github.io/Thirumurugan-Portfolio/" 
                               style="color: #000000; text-decoration: none;">
                               thirumurugan2001.github.io
                            </a>
                        </p>
                    </div>

                    <div class="section">
                        <p>In the meantime, feel free to explore my portfolio to learn more about my work in AI, Machine Learning, and full-stack development.</p>
                    </div>

                    <div class="signature">
                        <p>Warm regards,</p>
                        <p><strong>Thirumurugan Subramaniyan</strong></p>
                        <p>AI Full Stack Engineer</p>
                    </div>
                </div>

                <div class="footer">
                    <p style="margin: 0; font-size: 12px;">
                        This is an automated acknowledgement. For immediate assistance, please call +91 7339225958
                    </p>
                </div>
            </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(body, "html"))
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, app_password)
            server.sendmail(sender_email, user_email, msg.as_string())
        print("✅ Acknowledgement email sent to user successfully") 
        return True
    except Exception as e:
        print(f"❌ Error sending acknowledgement email: {str(e)}")
        return False